### ISSUE TITLE
TypeError: Cannot read property 'ETH' of undefined

### ISSUE THREAD

**Issue by jorisbontje** [nexusdev/dapple#338] opened 2016-10-20 12:21 UTC
when trying to deploy maker-otc to morden with dapple 0.8.9

```
$ dapple script run scripts/deploy_expiring_market.ds

/Users/mids/.node/lib/node_modules/dapple/node_modules/solc/soljson.js:1
(function (exports, require, module, __filename, __dirname) { var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=typeof window==="object";var ENVIRONMENT_IS_WORKER=typeof importScripts==="function";var ENVIRONMENT_IS_NODE=typeof process==="object"&&typeof require==="function"&&!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_WORKER;var ENVIRONMENT_IS_SHELL=!ENVIRONMENT_IS_WEB&&!ENVIRONMENT_IS_NODE&&!ENVIRONMENT_IS_WORKER;if(ENVIRONMENT_IS_NODE){if(!Module["print"])Module["print"]=function print(x){process["stdout"].write(x+"\n")};if(!Module["printErr"])Module["printErr"]=function printErr(x){process["stderr"].write(x+"\n")};var nodeFS=require("fs");var nodePath=require("path");Module["read"]=function read(filename,binary){filename=nodePath["normalize"](filename);var ret=nodeFS["readFileSync"]

TypeError: Cannot read property 'ETH' of undefined
    at Object.web3.eth.getBlock [as callback] (/Users/mids/.node/lib/node_modules/dapple/node_modules/dapple-core/chain_expert.js:16:40)
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/web3/lib/web3/method.js:142:25
    at /Users/mids/.node/lib/node_modules/dapple/node_modules/web3/lib/web3/requestmanager.js:89:9
    at request.onreadystatechange (/Users/mids/.node/lib/node_modules/dapple/node_modules/web3/lib/web3/httpprovider.js:114:13)
    at dispatchEvent (/Users/mids/.node/lib/node_modules/dapple/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
    at setState (/Users/mids/.node/lib/node_modules/dapple/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
    at IncomingMessage.<anonymous> (/Users/mids/.node/lib/node_modules/dapple/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
```

**Comment by mhhf** [comment] 2016-10-20 13:02
The new syntax would look like this
```
pragma solidity ^0.4.0;
import "dapple/script.sol";

contrat Deploy is Script {
  function Deploy() {
    var otc = new ExpiringMarket(1209600); // 604800 = 1 week; 1209600 = 2 weeks
    export("otc", otc);
  }
}
```

and you can run it via `dapple script run Deploy` ( not tested yet )

you need select the right chain in before of course via: 
`dapple chain new`
and point a remote chain to the endpoint, you want to deploy it to.

**Comment by dbrock** [comment] 2016-10-20 13:06
You should be able to write `new ExpiringMarket(2 weeks)`, right?

And inlining the expression should also not be a problem, correct? For example:

```
contract Deploy is Script {
  function Deploy() {
    export("market", new ExpiringMarket(2 weeks));
  }
}
```

**Comment by mhhf** [comment] 2016-10-20 13:29
Don't forget to also import the file where ExpiringMarket is defined.

**Comment by jorisbontje** [comment] 2016-10-20 13:39
Even with the new syntax I get the same `TypeError: Cannot read property 'ETH' of undefined` error.

```
pragma solidity ^0.4.2;

import "dapple/script.sol";
import "./expiring_market.sol";

contract DeployExpiringMarket is Script {
  function DeployExpiringMarket () {
    exportObject("otc", new ExpiringMarket(2 weeks));
  }
}
```

**Comment by mhhf** [comment] 2016-10-20 14:49
this was caused by an old `~/.dapple` version which was generated with some intermediate development version of dapple. Closing since removing `~/.dapple` solved this issue.

**Closed by mhhf** 2016-10-20 14:49 UTC
